name: Windows build

on: [push, pull_request]

env:
  # Customize the env if
  BUILD_TYPE: Release
  DPDK_VERSION: 22.07

jobs:
  Build:
    #if: github.repository == 'OpenVisualCloud/Media-Transport-Library'
    runs-on: [Windows, self-hosted]

    steps:
    - name: checkout kahawai repo
      uses: actions/checkout@v3
      with:
        path: kahawai
    
    - name: checkout dpdk repo
      uses: actions/checkout@v3
      with:
        repository: 'DPDK/dpdk'
        ref: v${{  env.DPDK_VERSION  }}
        path: dpdk

    - name: Apply patches
      run: |
        cd dpdk
        git am ../kahawai/dpdk/${{  DPDK_VERSION  }}/*.patch
      shell: bash
      
