name: Windows build

on: [push, pull_request]

env:
  # Customize the env if
  BUILD_TYPE: Release
  DPDK_VERSION: 22.07

jobs:
  Build:
    #if: github.repository == 'OpenVisualCloud/Media-Transport-Library'
    runs-on: [Windows, self-hosted]

    steps:
    - name: clean build content
      run: rm -r -fo c:\dpdk c:\libst_dpdk

    - name: checkout kahawai repo
      uses: actions/checkout@v3
      with:
        path: kahawai
    
    - name: checkout dpdk repo
      uses: actions/checkout@v3
      with:
        repository: 'DPDK/dpdk'
        ref: v${{  env.DPDK_VERSION  }}
        path: dpdk

    - name: Apply patches
      run: |
        cd dpdk
        git am ../kahawai/patches/dpdk/${{  env.DPDK_VERSION  }}/*.patch
        git am ../kahawai/patches/dpdk/${{  env.DPDK_VERSION  }}/windows/*.patch
      shell: bash
      
    - name: Build dpdk
      run: |
        cd dpdk
        meson build --prefix=C:\\dpdk
        ninja -C build install
        cd c:\dpdk\lib
        rm *.dll.a
        (gc "C:\dpdk\lib\pkgconfig\libdpdk.pc") | ForEach-Object {$_ -replace("Libs\..*","$libdpdkPc")} | Out-File -Encoding  ASCII "C:\dpdk\lib\pkgconfig\libdpdk.pc"
        (gc "C:\dpdk\lib\pkgconfig\libdpdk-libs.pc") | ForEach-Object {$_ -replace("^Libs:.*","$libdpdkLibsPc")} | Out-File -Encoding ASCII "C:\dpdk\lib\pkgconfig\libdpdk-libs.pc"
